// Generated by CoffeeScript 1.3.3
var Task, TimerCtrl, ToDoCtrl, notificateToDesktop;

angular.module('MyModule', []).filter('integer', function() {
  return function(input, num) {
    var out;
    out = (input >> 0).toString();
    while (out.length < num) {
      out = "0" + out;
    }
    return out;
  };
});

Task = (function() {

  function Task(body) {
    this.body = body;
    this.done = false;
    this.pomoCnt = 0;
  }

  return Task;

})();

notificateToDesktop = function(title, body, timeUpSec) {
  var notification, permission;
  if (typeof window.webkitNotifications === "undefined") {
    console.log("ブラウザがデスクトップ通知機能に対応していません。");
  }
  permission = webkitNotifications.checkPermission();
  switch (permission) {
    case 0:
      notification = webkitNotifications.createNotification("tomate.gif", title, body);
      notification.onclick = function(e) {
        return notification.cancel();
      };
      notification.show();
      if (timeUpSec > 0) {
        return setTimeout(function() {
          return notification.cancel();
        }, timeUpSec * 1000);
      }
      break;
    case 1:
      return webkitNotifications.requestPermission(function() {
        return alert("デスクトップ通知機能を設定しました");
      });
    case 2:
      return alert("デスクトップ通知機能が拒否されています");
  }
};

TimerCtrl = function($scope) {
  var ids, startTimer;
  ids = [];
  $scope.time = new Date(0, 0, 0, 0, 0, 0);
  $scope.stop = function() {
    var i, _i, _len;
    for (_i = 0, _len = ids.length; _i < _len; _i++) {
      i = ids[_i];
      clearInterval(i);
    }
    ids = [];
    return $scope.time = new Date(0, 0, 0, 0, 0, 0);
  };
  $scope.startPomodoro = function(task, min, sec) {
    return startTimer(min, sec, function() {
      task.pomoCnt--;
      notificateToDesktop("ポモドーロ終了", "ポモドーロが終了しました。休憩時間に入ります。", 10);
      return startTimer(5, 0, function() {
        return notificateToDesktop("休憩終了", "休憩時間が終了しました。");
      });
    });
  };
  return startTimer = function(min, sec, onFinish) {
    var i, id, _i, _len;
    for (_i = 0, _len = ids.length; _i < _len; _i++) {
      i = ids[_i];
      clearInterval(i);
    }
    ids = [];
    $scope.time = new Date(0, 0, 0, 0, min, sec);
    id = setInterval(function() {
      $scope.time.setSeconds($scope.time.getSeconds() - 1);
      $scope.$apply();
      if ($scope.time.getSeconds() === 0 && $scope.time.getMinutes() === 0) {
        clearInterval(id);
        ids = [];
        if (onFinish) {
          return onFinish();
        }
      }
    }, 1000);
    return ids.push(id);
  };
};

ToDoCtrl = function($scope) {
  $scope.tasks = [];
  $scope.addNew = function() {
    $scope.tasks.push(new Task($scope.newTaskBody));
    return $scope.newTaskBody = "";
  };
  $scope.getDoneCount = function() {
    var count;
    count = 0;
    angular.forEach($scope.tasks, function(task) {
      if (task.done) {
        return count += 1;
      }
    });
    return count;
  };
  $scope.deleteDone = function() {
    var oldTasks;
    oldTasks = $scope.tasks;
    $scope.tasks = [];
    return angular.forEach(oldTasks, function(task) {
      if (!task.done) {
        return $scope.tasks.push(task);
      }
    });
  };
  $scope.addPomodoro = function(index) {
    return $scope.tasks[index].pomoCnt++;
  };
  $scope.deletePomodoro = function(index) {
    if ($scope.tasks[index].pomoCnt > 0) {
      return $scope.tasks[index].pomoCnt--;
    }
  };
  return $scope.startPomo = function(task) {
    if (task.pomoCnt > 0) {
      return $scope.startPomodoro(task, 25, 0);
    }
  };
};
